version: '2'
services:
  postgres:
    volumes:
      - ./docker/data/db/postgres:/var/lib/postgresql/data
    build: ./postgres
  adminer:
    image: clue/adminer
    ports:
      - "99:80"
  app:
    build: ./app
    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
  mongo:
    volumes:
      - ./docker/data/db/mongo:/data/db/
    ports:
      - "27017:27017"
    build: ./mongo