version: '2'
services:
  postgres:
    volumes:
      - ./docker/data/db/postgres:/var/lib/postgresql/data
    build: ./postgres
  adminer:
    image: clue/adminer
    ports:
      - "99:80"
  app:
    build: ./app
    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
  mongo:
    volumes:
      - /docker/data/db/mongo
    ports:
      - "27017:27017"
    image:
      mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: mongo