version: '3.7'
services:
  postgres:
    build:
      context: ./postgres
  adminer:
    image: clue/adminer
    ports:
      - "99:80"
  app:
    build: ./app
    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
#   output stat files to /dont/do/ in python, sync here into ./docker/pylo
    volumes:
      - ./docker/pylo:/dont/do/
  mongo:
    ports:
      - "27017:27017"
    build: ./mongo