version: '3.7'
services:
  postgres-data:
    volumes:
      - ./docker/data/db/postgres:/var/lib/postgresql/data
    build:
      context: ./postgres
      target: data
  postgres-runner:
    build:
      context: ./postgres
      target: runner
  adminer:
    image: clue/adminer
    ports:
      - "99:80"
  app:
    build: ./app
    depends_on:
      - mongo
      - postgres-runner
    links:
      - mongo
      - postgres-runner
  mongo:
    volumes:
      - ./docker/data/db/mongo:/data/db/
    ports:
      - "27017:27017"
    build: ./mongo